// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// initLogger is an autogenerated mock type for the initLogger type
type initLogger struct {
	mock.Mock
}

// InitLogger provides a mock function with given fields:
func (_m *initLogger) InitLogger() {
	_m.Called()
}

type newInitLoggerT interface {
	mock.TestingT
	Cleanup(func())
}

// newInitLogger creates a new instance of initLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newInitLogger(t newInitLoggerT) *initLogger {
	mock := &initLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
