// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	ports "gitlab.sce-ovoo.pl/ovoo/products/chain4energy/billing/c4e-iges.git/internal/core/ports"
)

// InvoicePublisherFactory is an autogenerated mock type for the InvoicePublisherFactory type
type InvoicePublisherFactory struct {
	mock.Mock
}

// MakePublisher provides a mock function with given fields:
func (_m *InvoicePublisherFactory) MakePublisher() ports.InvoicePublisher {
	ret := _m.Called()

	var r0 ports.InvoicePublisher
	if rf, ok := ret.Get(0).(func() ports.InvoicePublisher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.InvoicePublisher)
		}
	}

	return r0
}

type NewInvoicePublisherFactoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewInvoicePublisherFactory creates a new instance of InvoicePublisherFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInvoicePublisherFactory(t NewInvoicePublisherFactoryT) *InvoicePublisherFactory {
	mock := &InvoicePublisherFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
