// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// InvoiceStoreRepo is an autogenerated mock type for the InvoiceStoreRepo type
type InvoiceStoreRepo struct {
	mock.Mock
}

// StoreMany provides a mock function with given fields: ctx, documents
func (_m *InvoiceStoreRepo) StoreMany(ctx context.Context, documents ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, documents...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) error); ok {
		r0 = rf(ctx, documents...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreManyWithinTransaction provides a mock function with given fields: ctx, documents
func (_m *InvoiceStoreRepo) StoreManyWithinTransaction(ctx context.Context, documents ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, documents...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...interface{}) error); ok {
		r0 = rf(ctx, documents...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreOne provides a mock function with given fields: ctx, document
func (_m *InvoiceStoreRepo) StoreOne(ctx context.Context, document interface{}) error {
	ret := _m.Called(ctx, document)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewInvoiceStoreRepoT interface {
	mock.TestingT
	Cleanup(func())
}

// NewInvoiceStoreRepo creates a new instance of InvoiceStoreRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInvoiceStoreRepo(t NewInvoiceStoreRepoT) *InvoiceStoreRepo {
	mock := &InvoiceStoreRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
