/*
BMSFES. 
Copyright (C) 2022-2035 

This file is part of the BMSFES solution. 
BMSFES is free software: you can redistribute it and/or modify 
it under the terms of the GNU Affero General Public License as 
published by the Free Software Foundation, either version 3 of the 
License, or (at your option) any later version.
 
BMSFES solution is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License 
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	invoice "gitlab.sce-ovoo.pl/ovoo/products/chain4energy/billing/billing.git/pkg/invoice"
)

// InvoiceEventValidator is an autogenerated mock type for the InvoiceEventValidator type
type InvoiceEventValidator struct {
	mock.Mock
}

// ValidateInvoiceEvent provides a mock function with given fields: ctx, invoiceEvent
func (_m *InvoiceEventValidator) ValidateInvoiceEvent(ctx context.Context, invoiceEvent *invoice.InvoiceEvent) error {
	ret := _m.Called(ctx, invoiceEvent)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *invoice.InvoiceEvent) error); ok {
		r0 = rf(ctx, invoiceEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewInvoiceEventValidatorT interface {
	mock.TestingT
	Cleanup(func())
}

// NewInvoiceEventValidator creates a new instance of InvoiceEventValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInvoiceEventValidator(t NewInvoiceEventValidatorT) *InvoiceEventValidator {
	mock := &InvoiceEventValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
