// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	ports "gitlab.sce-ovoo.pl/ovoo/products/chain4energy/billing/c4e-iges.git/internal/core/ports"
)

// InvoiceRepoFactory is an autogenerated mock type for the InvoiceRepoFactory type
type InvoiceRepoFactory struct {
	mock.Mock
}

// MakeRepo provides a mock function with given fields:
func (_m *InvoiceRepoFactory) MakeRepo() ports.InvoiceRepo {
	ret := _m.Called()

	var r0 ports.InvoiceRepo
	if rf, ok := ret.Get(0).(func() ports.InvoiceRepo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.InvoiceRepo)
		}
	}

	return r0
}

type NewInvoiceRepoFactoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewInvoiceRepoFactory creates a new instance of InvoiceRepoFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInvoiceRepoFactory(t NewInvoiceRepoFactoryT) *InvoiceRepoFactory {
	mock := &InvoiceRepoFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
