// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package api

import ( 
	"encoding/json"
	"fmt"
)

const DATE_LAYOUT = "2006-01-02"
const INTERNAL_DATE_LAYOUT = "02/01/2006"

// Error defines model for Error.
type Error struct {
	// Error code
	Code int `json:"code"`

	// Error message
	Message string `json:"message"`
}

// SellSummaryItem defines model for SellSummaryItem.
type SellSummaryItem struct {
	Code       string  `json:"code"`
	GrossValue float64 `json:"grossValue"`
	Name       string  `json:"name"`
	NetValue   float64 `json:"netValue"`
	TaxValue   float64 `json:"taxValue"`
	VatRate    float64 `json:"vatRate"`
}

// CustomerDetails model
type CustomerDetails struct {
	CustomerId  string  `json:"customerId"`
	DisplayName *string `json:"displayName,omitempty"`
	FirstName   *string `json:"firstName,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Nip         *string `json:"nip,omitempty"`
	Regon       *string `json:"regon,omitempty"`
}

// InvoiceDetails model
type InvoiceDetails struct {
	BillingEndDate   string `json:"billingEndDate"`
	BillingStartDate string `json:"billingStartDate"`
	CustomerId       string `json:"customerId"`
	InvoiceNumber    string `json:"invoiceNumber"`
	IssueDate        string `json:"issueDate"`
	PaymentDueDate   string `json:"paymentDueDate"`
	ServiceDate      string `json:"serviceDate"`
	Status           string `json:"status"`
	BankAccountNumber string `json:"bankAccountNumber"`
}

// Total model
type Total struct {
	GrossValue float64 `json:"grossValue"`
	NetValue   float64 `json:"netValue"`
	TaxValue   float64 `json:"taxValue"`
}

// SellSummary model
type SellSummary struct {
	GeneralInformation *[]SellSummaryItem `json:"general_information,omitempty"`
	Total *Total `json:"total,omitempty"`
}

// SummaryInvoice defines model for SummaryInvoice.
type SummaryInvoice struct {
	Header struct {
		Content struct {
			Type *string `json:"type,omitempty"`
		} `json:"content"`

		// Provider
		Provider string `json:"provider"`

		// Version of the document type
		Version string `json:"version"`
	} `json:"header"`
	Payload struct {
		CustomerDetails *CustomerDetails `json:"customerDetails,omitempty"`
		InvoiceDetails InvoiceDetails `json:"invoiceDetails"`
		SellSummary *SellSummary `json:"sellSummary,omitempty"`
	} `json:"payload"`
}

func (i SummaryInvoice) String() string {
	data, _ := json.MarshalIndent(i, "", "\t")
	return fmt.Sprintf("%s", data)
}

func (i SummaryInvoice) Encode() ([]byte, error) {
	return json.Marshal(i)
}

// GetSummaryInvoicesByDateRangeParams defines parameters for GetSummaryInvoicesByDateRange.
type GetSummaryInvoicesByDateRangeParams struct {
	// The date based field name being used as a filter
	SelectBy string `form:"selectBy" json:"selectBy"`

	// The start date
	StartAt string `form:"startAt" json:"startAt"`

	// The end date
	EndAt *string `form:"endAt,omitempty" json:"endAt,omitempty"`
}
