apiVersion: v1
data:
  email-notification-service.yaml: |+
    service:
      ServiceName: Email-Notification-App
      TestMode: true
      WorkerPoolSize: 1
      ErrorEmailTo: ["info@chain4.energy"]
      ErrorEmailEnvironment: dev
    
    conversion:
      Url: http://conversion-service
      Timeout: 60
    
    smtp:
      Host: smtp.gmail.com
      Port: 587
      User: user
      Password: pass
      SenderName: Platforma Dla Energii - Powiadomienie
      Security: None
    
    rabbitmq:
      QueueName: email-que
      QueueType: quorum
      IsAutoAck: false
      PrefetchCount: 1
      RabbitMQConfig:
        RabbitUrl: "amqp://user:vqrtScJ92h@rabbitmq-ovoo.rabbitmq-ovoo.svc.cluster.local:5672/"
        IsDurable: true
        IsAutoDelete: false
    
    logger:
      Development: true
      DisableCaller: false
      DisableStacktrace: false
      Encoding: console
      Level: info
kind: ConfigMap
metadata:
  name: ens-config