export enum ApiTypeEnum{
  USER_API = 'USER_API',
  USERS_API = 'USERS_API',
  CUSTOMER_API = 'CUSTOMER_API',
  PROVIDER_API = 'PROVIDER_API',
  OFFERS_API = 'OFFERS_API',
  INVOICE_API = 'INVOICE_API',
  CONTRACT_API = 'CONTRACT_API',
  WORKER_API = 'WORKER_API',
  DRAFT_OFFERS_API = 'DRAFT_OFFERS_API',
  INSTALLATION_API = 'INSTALLATION_API',
  PRICING_API = 'PRICING_API',
  PDF_CONVERTER_API = 'PDF_CONVERTER_API',
  TARRIF_GROUP_API = 'TARRIF_GROUP_API'
}
