export enum ServiceTypeEnum {
  ROUTER = 'ROUTER',
  AUTH_SERVICE = 'AUTH_SERVICE',
  GLOBAL_ERROR_HANDLER = 'GLOBAL_ERROR_HANDLER',
  CONTRACTS_SERVICE= 'CONTRACTS_SERVICE',
  INVOICES_SERVICE= 'INVOICES_SERVICE',
  OFFERS_SERVICE= 'OFFERS_SERVICE',
  USERS_SERVICE= 'USERS_SERVICE',
  PROVIDERS_SERVICE = 'PROVIDERS_SERVICE',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  INSTALLATIONS_SERVICE = 'INSTALLATIONS_SERVICE',
  EMPLOYEES_SERVICE = 'EMPLOYEES_SERVICE',
  PRICING_SERVICE = 'PRICING_SERVICE',
  TARIFF_SERVICE = 'TARIFF_SERVICE',
  TARIFF_GROUP_SERVICE = 'TARIFF_GROUP_SERVICE',
  THEME_SERVICE = 'THEME_SERVICE',
  SUPER_ADMINS_SERVICE = 'SUPER_ADMINS_SERVICE',
  PROVIDER_ADMINS_SERVICE = 'PROVIDER_ADMINS_SERVICE'
}
