export enum FeatureEnum {
  MANAGE_SUPER_ADMIN ,
  MANAGE_FULL_ADMIN ,
  MANAGE_ADMIN ,
  MANAGE_TRADER ,
  MANAGE_SUPER_AGENT ,
  MANAGE_AGENT ,
  MANAGE_PROSUMER ,

  RESEND_ACTIVATION_LINK,

  MANAGE_PRICING,
  MANAGE_OFFER_DRAFTS,
  MANAGE_OFFERS,
  MANAGE_PARTNERS
}
