export enum RoleEnum {
  // SUPER_ADMIN= 'SUPER_ADMIN',
  // ADMINISTRATOR_FULL= 'ADMINISTRATOR_FULL',
  // ADMINISTRATOR_BASIC= 'ADMINISTRATOR_BASIC',
  // TRADER= 'TRADER',
  // SUPER_AGENT= 'SUPER_AGENT',
  // AGENT= 'AGENT',
  // PROSUMER= 'PROSUMER'
  UNDEFINED = 0,
  SUPER_ADMIN= 1,
  ADMINISTRATOR_FULL= 2,
  ADMINISTRATOR_BASIC= 3,
  TRADER= 4,
  SUPER_AGENT= 5,
  AGENT= 6,
  PROSUMER= 7
}
