swagger: "2.0"
info:
  title: C4E signer service RESTFull API
  description: Service responsible for signing documents
  version: 1.0.0
host: localhost:8183
schemes:
  - http
basePath: /api/signer
tags:
  - name: Init
  - name: SigningCompletedNotification
paths:
  /initSign:
    post:
      tags: [ Init ]
      operationId: Init
      parameters:
        - in: body
          name: contract
          required: true
          schema:
            $ref: '#/definitions/Contract'
      responses:
        200:
          description: Hauth
          schema:
            $ref: '#/definitions/Hauth'
        403:
          description: StatusForbidden
  /signingCompletedNotification:
    post:
      tags: [ SigningCompletedNotification ]
      operationId: SigningCompletedNotification
      parameters:
        - in: path
          name: signingId
          required: true
          type: string
      responses:
        200:
          description: Signing completed
        403:
          description: StatusForbidden

# DEFINITIONS
definitions:
  Contract:
    type: object
    required:
      - _id
      - header
      - payload
    properties:
      _id:
        type: string
      header:
        type: Header
      payload:
        type: ContractPayload
  Hauth:
    type: object
    required:
      - hauth
    properties:
      hauth:
        type: string
        example: eyJ0aW1lc3RhbXAiOjE2NzExMTE5Nzk1OTAsIm1vZGUiOiJTSE9SVF9URVJNIiwidXJsU2lnbmluZ0NvbXBsZXRlZCI6Imh0dHA6Ly8xOTIuMTY4LjAuMS9wYXJ0bmVyLXBvcnRhbC9vcGVyYXRpb24tY29tcGxldGVkIiwiaWRwTGlzdCI6WyJJRFAxIiwiSURQMiJdLCJobWFjIjoiOGM5ZmJhN2E1NzAzMDI2NWE3MzM0ZjFjNTY2MDFjZTM1YTM4MzI4MzI5Y2ZhZDdiYTNlNGZjNmM3ZjI2Y2I1NSJ9
