-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 09:24:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema c4e
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c4e
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c4e` DEFAULT CHARACTER SET utf8 ;
USE `c4e` ;

-- -----------------------------------------------------
-- Table `c4e`.`PROVIDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`PROVIDER` ;

CREATE TABLE IF NOT EXISTS `c4e`.`PROVIDER` (
                                                `ID` INT NOT NULL AUTO_INCREMENT,
                                                `NAME` VARCHAR(45) NOT NULL,
                                                `STATUS` TINYINT NOT NULL,
                                                `REGON` VARCHAR(45) NULL,
                                                `NIP` VARCHAR(45) NOT NULL,
                                                `KRS` VARCHAR(45) NULL,
                                                `EMAIL` VARCHAR(45) NULL,
                                                `PHONE_NUMBER` VARCHAR(45) NULL,
                                                `BUILDING_NUMBER` VARCHAR(45) NULL,
                                                `APARTMENT_NUMBER` VARCHAR(45) NULL,
                                                `POSTAL_CODE` VARCHAR(45) NULL,
                                                `PROVINCE` VARCHAR(45) NULL,
                                                `CITY` VARCHAR(45) NULL,
                                                `COUNTRY` VARCHAR(45) NULL,
                                                `BLOCKCHAIN_ACC_ADDRESS` VARCHAR(45) NULL,
                                                `LICENSE_ID` VARCHAR(45) NULL,
                                                `LICENSE_EXPIRATION_DATE` DATE NULL,
                                                `LICENSE_AREA` VARCHAR(45) NULL,
                                                PRIMARY KEY (`ID`),
                                                UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC),
                                                UNIQUE INDEX `KRS_UNIQUE` (`KRS` ASC),
                                                UNIQUE INDEX `NIP_UNIQUE` (`NIP` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`CUSTOMER_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`CUSTOMER_TYPE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`CUSTOMER_TYPE` (
                                                     `NAME` ENUM('CONSUMER', 'PROSUMER', 'PRODUCER') NOT NULL,
                                                     PRIMARY KEY (`NAME`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`CUSTOMER_ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`CUSTOMER_ACCOUNT` ;

CREATE TABLE IF NOT EXISTS `c4e`.`CUSTOMER_ACCOUNT` (
                                                        `ID` INT NOT NULL AUTO_INCREMENT,
                                                        `FIRST_NAME` VARCHAR(45) NULL,
                                                        `LAST_NAME` VARCHAR(45) NULL,
                                                        `EMAIL` VARCHAR(45) NULL,
                                                        `PHONE` VARCHAR(45) NULL,
                                                        `STATUS` TINYINT NULL,
                                                        `NIP` VARCHAR(45) NULL,
                                                        `PESEL` VARCHAR(45) NULL,
                                                        `REGON` VARCHAR(45) NULL,
                                                        `STREET` VARCHAR(45) NULL,
                                                        `BUILDING_NUMBER` VARCHAR(45) NULL,
                                                        `APARTMENT_NUMBER` VARCHAR(45) NULL,
                                                        `POSTAL_CODE` VARCHAR(45) NULL,
                                                        `CITY` VARCHAR(45) NULL,
                                                        `PROVINCE` VARCHAR(45) NULL,
                                                        `COUNTRY` VARCHAR(45) NULL,
                                                        `BANK_ACC_NUMBER` VARCHAR(26) NULL,
                                                        `PROVIDER_ID` INT NOT NULL,
                                                        `CUSTOMER_TYPE_NAME` ENUM('CONSUMER', 'PROSUMER', 'PRODUCER') NOT NULL,
                                                        PRIMARY KEY (`ID`),
                                                        INDEX `fk_Account_Provider_idx` (`PROVIDER_ID` ASC),
                                                        UNIQUE INDEX `BANK_ACC_NUMBER_UNIQUE` (`BANK_ACC_NUMBER` ASC),
                                                        INDEX `fk_CUSTOMER_ACCOUNT_CUSTOMER_TYPE1_idx` (`CUSTOMER_TYPE_NAME` ASC),
                                                        CONSTRAINT `fk_Account_Provider`
                                                            FOREIGN KEY (`PROVIDER_ID`)
                                                                REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_CUSTOMER_ACCOUNT_CUSTOMER_TYPE1`
                                                            FOREIGN KEY (`CUSTOMER_TYPE_NAME`)
                                                                REFERENCES `c4e`.`CUSTOMER_TYPE` (`NAME`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`BALANCE_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`BALANCE_TYPE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`BALANCE_TYPE` (
                                                    `NAME` VARCHAR(45) NOT NULL,
                                                    PRIMARY KEY (`NAME`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`ACCOUNT_BALANCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`ACCOUNT_BALANCE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`ACCOUNT_BALANCE` (
                                                       `ID` INT NOT NULL AUTO_INCREMENT,
                                                       `NAME` VARCHAR(45) NULL,
                                                       `STATUS` TINYINT NULL,
                                                       `UNITS` INT NULL,
                                                       `ACCOUNT_ID` INT NOT NULL,
                                                       `PROVIDER_ID` INT NOT NULL,
                                                       `BALANCE_TYPE_NAME` VARCHAR(45) NOT NULL,
                                                       PRIMARY KEY (`ID`),
                                                       INDEX `fk_AccountBalance_Account1_idx` (`ACCOUNT_ID` ASC),
                                                       INDEX `fk_AccountBalance_Provider1_idx` (`PROVIDER_ID` ASC),
                                                       INDEX `fk_ACCOUNT_BALANCE_BALANCE_TYPE1_idx` (`BALANCE_TYPE_NAME` ASC),
                                                       CONSTRAINT `fk_AccountBalance_Account1`
                                                           FOREIGN KEY (`ACCOUNT_ID`)
                                                               REFERENCES `c4e`.`CUSTOMER_ACCOUNT` (`ID`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_AccountBalance_Provider1`
                                                           FOREIGN KEY (`PROVIDER_ID`)
                                                               REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_ACCOUNT_BALANCE_BALANCE_TYPE1`
                                                           FOREIGN KEY (`BALANCE_TYPE_NAME`)
                                                               REFERENCES `c4e`.`BALANCE_TYPE` (`NAME`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`RATING_PLAN_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`RATING_PLAN_TYPE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`RATING_PLAN_TYPE` (
                                                        `ID` INT NOT NULL,
                                                        `NAME` ENUM('SALE', 'REPURCHASE', 'RDN') NOT NULL,
                                                        PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`TARIFF_GROUP_LABEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`TARIFF_GROUP_LABEL` ;

CREATE TABLE IF NOT EXISTS `c4e`.`TARIFF_GROUP_LABEL` (
                                                          `NAME` VARCHAR(45) NOT NULL,
                                                          PRIMARY KEY (`NAME`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`RATING_PLAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`RATING_PLAN` ;

CREATE TABLE IF NOT EXISTS `c4e`.`RATING_PLAN` (
                                                   `ID` BIGINT NOT NULL AUTO_INCREMENT,
                                                   `INTERNAL_ID` VARCHAR(45) NULL,
                                                   `NAME` VARCHAR(45) NOT NULL,
                                                   `NET_COMMERCIAL_FEE` FLOAT NOT NULL,
                                                   `PROVIDER_ID` INT NOT NULL,
                                                   `START_DATE` DATETIME NOT NULL,
                                                   `END_DATE` DATETIME NOT NULL,
                                                   `TARIFF_GROUP_LABEL_NAME` VARCHAR(45) NOT NULL,
                                                   `RATING_PLAN_TYPE_ID` INT NOT NULL,
                                                   PRIMARY KEY (`ID`),
                                                   INDEX `fk_RATING_PLAN_PROVIDER1_idx` (`PROVIDER_ID` ASC),
                                                   INDEX `fk_RATING_PLAN_TARIFF_GROUP_LABEL1_idx` (`TARIFF_GROUP_LABEL_NAME` ASC),
                                                   UNIQUE INDEX `INTERNAL_ID_UNIQUE` (`INTERNAL_ID` ASC),
                                                   INDEX `fk_RATING_PLAN_RATING_PLAN_TYPE1_idx` (`RATING_PLAN_TYPE_ID` ASC),
                                                   CONSTRAINT `fk_RATING_PLAN_PROVIDER1`
                                                       FOREIGN KEY (`PROVIDER_ID`)
                                                           REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_RATING_PLAN_TARIFF_GROUP_LABEL1`
                                                       FOREIGN KEY (`TARIFF_GROUP_LABEL_NAME`)
                                                           REFERENCES `c4e`.`TARIFF_GROUP_LABEL` (`NAME`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_RATING_PLAN_RATING_PLAN_TYPE1`
                                                       FOREIGN KEY (`RATING_PLAN_TYPE_ID`)
                                                           REFERENCES `c4e`.`RATING_PLAN_TYPE` (`ID`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`SERVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`SERVICE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`SERVICE` (
                                               `ID` BIGINT NOT NULL AUTO_INCREMENT,
                                               `NAME` VARCHAR(45) NOT NULL,
                                               `TYPE` ENUM('SALE', 'REPURCHASE') NULL,
                                               `PROVIDER_ID` INT NOT NULL,
                                               PRIMARY KEY (`ID`),
                                               INDEX `fk_SERVICE_PROVIDER1_idx` (`PROVIDER_ID` ASC),
                                               UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC),
                                               UNIQUE INDEX `PROVIDER_ID_UNIQUE` (`PROVIDER_ID` ASC),
                                               CONSTRAINT `fk_SERVICE_PROVIDER1`
                                                   FOREIGN KEY (`PROVIDER_ID`)
                                                       REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`SERVICE_OFFER_GROUP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`SERVICE_OFFER_GROUP` ;

CREATE TABLE IF NOT EXISTS `c4e`.`SERVICE_OFFER_GROUP` (
                                                           `ID` BIGINT NOT NULL AUTO_INCREMENT,
                                                           `NAME` VARCHAR(45) NOT NULL,
                                                           `IS_ACTIVE` TINYINT NULL,
                                                           `START_DATE` DATETIME NULL,
                                                           `END_DATE` DATETIME NULL,
                                                           `STATUS` ENUM('DRAFT', 'FINAL', 'SENT', 'DELIVERED', 'NEGOTIATION') NULL,
                                                           `PROVIDER_ID` INT NOT NULL,
                                                           PRIMARY KEY (`ID`),
                                                           INDEX `fk_SERVICE_OFFER_GROUP_PROVIDER1_idx` (`PROVIDER_ID` ASC),
                                                           UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC),
                                                           CONSTRAINT `fk_SERVICE_OFFER_GROUP_PROVIDER1`
                                                               FOREIGN KEY (`PROVIDER_ID`)
                                                                   REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`SERVICE_OFFER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`SERVICE_OFFER` ;

CREATE TABLE IF NOT EXISTS `c4e`.`SERVICE_OFFER` (
                                                     `ID` BIGINT NOT NULL AUTO_INCREMENT,
                                                     `NAME` VARCHAR(45) NULL,
                                                     `SERVICE_ID` BIGINT NOT NULL,
                                                     `RATING_PLAN_ID` BIGINT NOT NULL,
                                                     `PROVIDER_ID` INT NOT NULL,
                                                     `SERVICE_OFFER_GROUP_ID` BIGINT NOT NULL,
                                                     PRIMARY KEY (`ID`),
                                                     INDEX `fk_SERVICE_OFFER_SERVICE1_idx` (`SERVICE_ID` ASC),
                                                     INDEX `fk_SERVICE_OFFER_RATING_PLAN1_idx` (`RATING_PLAN_ID` ASC),
                                                     INDEX `fk_SERVICE_OFFER_PROVIDER1_idx` (`PROVIDER_ID` ASC),
                                                     UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC),
                                                     UNIQUE INDEX `PROVIDER_ID_UNIQUE` (`PROVIDER_ID` ASC),
                                                     INDEX `fk_SERVICE_OFFER_SERVICE_OFFER_GROUP1_idx` (`SERVICE_OFFER_GROUP_ID` ASC),
                                                     CONSTRAINT `fk_SERVICE_OFFER_SERVICE1`
                                                         FOREIGN KEY (`SERVICE_ID`)
                                                             REFERENCES `c4e`.`SERVICE` (`ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_SERVICE_OFFER_RATING_PLAN1`
                                                         FOREIGN KEY (`RATING_PLAN_ID`)
                                                             REFERENCES `c4e`.`RATING_PLAN` (`ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_SERVICE_OFFER_PROVIDER1`
                                                         FOREIGN KEY (`PROVIDER_ID`)
                                                             REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_SERVICE_OFFER_SERVICE_OFFER_GROUP1`
                                                         FOREIGN KEY (`SERVICE_OFFER_GROUP_ID`)
                                                             REFERENCES `c4e`.`SERVICE_OFFER_GROUP` (`ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`ACCOUNT_SUBSCRIPTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`ACCOUNT_SUBSCRIPTION` ;

CREATE TABLE IF NOT EXISTS `c4e`.`ACCOUNT_SUBSCRIPTION` (
                                                            `NAME` VARCHAR(45) NOT NULL,
                                                            `STATUS` TINYINT NULL,
                                                            `PRIORITY` INT NULL,
                                                            `START_DATE` DATETIME NULL,
                                                            `END_DATE` DATETIME NULL,
                                                            `SERVICE_OFFER_GROUP_ID` BIGINT NOT NULL,
                                                            `ACCOUNT_ID` INT NOT NULL,
                                                            `PROVIDER_ID` INT NOT NULL,
                                                            INDEX `fk_ACCOUNT_SUBSCRIPTION_SERVICE_OFFER_GROUP1_idx` (`SERVICE_OFFER_GROUP_ID` ASC),
                                                            INDEX `fk_ACCOUNT_SUBSCRIPTION_ACCOUNT1_idx` (`ACCOUNT_ID` ASC),
                                                            INDEX `fk_ACCOUNT_SUBSCRIPTION_PROVIDER1_idx` (`PROVIDER_ID` ASC),
                                                            UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC),
                                                            PRIMARY KEY (`ACCOUNT_ID`, `PROVIDER_ID`, `SERVICE_OFFER_GROUP_ID`),
                                                            CONSTRAINT `fk_ACCOUNT_SUBSCRIPTION_SERVICE_OFFER_GROUP1`
                                                                FOREIGN KEY (`SERVICE_OFFER_GROUP_ID`)
                                                                    REFERENCES `c4e`.`SERVICE_OFFER_GROUP` (`ID`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION,
                                                            CONSTRAINT `fk_ACCOUNT_SUBSCRIPTION_ACCOUNT1`
                                                                FOREIGN KEY (`ACCOUNT_ID`)
                                                                    REFERENCES `c4e`.`CUSTOMER_ACCOUNT` (`ID`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION,
                                                            CONSTRAINT `fk_ACCOUNT_SUBSCRIPTION_PROVIDER1`
                                                                FOREIGN KEY (`PROVIDER_ID`)
                                                                    REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`SERVICE_ACCESS_POINT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`SERVICE_ACCESS_POINT` ;

CREATE TABLE IF NOT EXISTS `c4e`.`SERVICE_ACCESS_POINT` (
                                                            `ID` INT NOT NULL AUTO_INCREMENT,
                                                            `SAP_CODE` VARCHAR(45) NULL,
                                                            `METER_NUMBER` VARCHAR(45) NOT NULL,
                                                            `CITY` VARCHAR(45) NULL,
                                                            `ADDRESS` VARCHAR(45) NULL,
                                                            `ACCOUNT_ID` INT NOT NULL,
                                                            PRIMARY KEY (`ID`),
                                                            INDEX `fk_ENERGY_POINT_ACCOUNT1_idx` (`ACCOUNT_ID` ASC),
                                                            UNIQUE INDEX `METER_NUMBER_UNIQUE` (`METER_NUMBER` ASC),
                                                            CONSTRAINT `fk_SERVICE_ACCESS_POINT_ACCOUNT1`
                                                                FOREIGN KEY (`ACCOUNT_ID`)
                                                                    REFERENCES `c4e`.`CUSTOMER_ACCOUNT` (`ID`)
                                                                    ON DELETE NO ACTION
                                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`DISTRIBUTION_NETWORK_OPERATOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`DISTRIBUTION_NETWORK_OPERATOR` ;

CREATE TABLE IF NOT EXISTS `c4e`.`DISTRIBUTION_NETWORK_OPERATOR` (
                                                                     `ID` INT NOT NULL AUTO_INCREMENT,
                                                                     `NAME` VARCHAR(45) NULL,
                                                                     `NIP` VARCHAR(45) NULL,
                                                                     `ADDRESS` VARCHAR(45) NULL,
                                                                     `CITY` VARCHAR(45) NULL,
                                                                     PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`CONTRACT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`CONTRACT` ;

CREATE TABLE IF NOT EXISTS `c4e`.`CONTRACT` (
                                                `ID` BIGINT NOT NULL AUTO_INCREMENT,
                                                `STATUS` ENUM('DRAFT', 'FINAL', 'SENT', 'DELIVERED', 'ACCEPTED') NOT NULL,
                                                `NUMBER` VARCHAR(45) NOT NULL,
                                                PRIMARY KEY (`ID`),
                                                UNIQUE INDEX `NUMBER_UNIQUE` (`NUMBER` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`SERVICE_ACCESS_POINT_CONTRACT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`SERVICE_ACCESS_POINT_CONTRACT` ;

CREATE TABLE IF NOT EXISTS `c4e`.`SERVICE_ACCESS_POINT_CONTRACT` (
                                                                     `CONTRACT_ID` BIGINT NOT NULL,
                                                                     `ANNUAL_ENERGY_USAGE` INT NULL,
                                                                     `ANNUAL_ENERGY_USAGE_UNITS` ENUM('kWh', 'MWh') NULL,
                                                                     `SERVICE_ACCESS_POINT_ID` INT NOT NULL,
                                                                     INDEX `fk_SERVICE_ACCESS_POINT_CONTRACT_CONTRACT1_idx` (`CONTRACT_ID` ASC),
                                                                     UNIQUE INDEX `CONTRACT_ID_UNIQUE` (`CONTRACT_ID` ASC),
                                                                     INDEX `fk_SERVICE_ACCESS_POINT_CONTRACT_SERVICE_ACCESS_POINT1_idx` (`SERVICE_ACCESS_POINT_ID` ASC),
                                                                     CONSTRAINT `fk_SERVICE_ACCESS_POINT_CONTRACT_CONTRACT1`
                                                                         FOREIGN KEY (`CONTRACT_ID`)
                                                                             REFERENCES `c4e`.`CONTRACT` (`ID`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION,
                                                                     CONSTRAINT `fk_SERVICE_ACCESS_POINT_CONTRACT_SERVICE_ACCESS_POINT1`
                                                                         FOREIGN KEY (`SERVICE_ACCESS_POINT_ID`)
                                                                             REFERENCES `c4e`.`SERVICE_ACCESS_POINT` (`ID`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`ACCOUNT_SUBSCRIPTION_CONTRACT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`ACCOUNT_SUBSCRIPTION_CONTRACT` ;

CREATE TABLE IF NOT EXISTS `c4e`.`ACCOUNT_SUBSCRIPTION_CONTRACT` (
                                                                     `CONTRACT_ID` BIGINT NOT NULL,
                                                                     `ACCOUNT_SUBSCRIPTION_ACCOUNT_ID` INT NOT NULL,
                                                                     `ACCOUNT_SUBSCRIPTION_PROVIDER_ID` INT NOT NULL,
                                                                     `ACCOUNT_SUBSCRIPTION_SERVICE_OFFER_GROUP_ID` BIGINT NOT NULL,
                                                                     INDEX `fk_ACCOUNT_SUBSCRIPTION_CONTRACT_CONTRACT1_idx` (`CONTRACT_ID` ASC),
                                                                     INDEX `fk_ACCOUNT_SUBSCRIPTION_CONTRACT_ACCOUNT_SUBSCRIPTION1_idx` (`ACCOUNT_SUBSCRIPTION_ACCOUNT_ID` ASC, `ACCOUNT_SUBSCRIPTION_PROVIDER_ID` ASC, `ACCOUNT_SUBSCRIPTION_SERVICE_OFFER_GROUP_ID` ASC),
                                                                     PRIMARY KEY (`CONTRACT_ID`),
                                                                     UNIQUE INDEX `CONTRACT_ID_UNIQUE` (`CONTRACT_ID` ASC),
                                                                     UNIQUE INDEX `ACCOUNT_SUBSCRIPTION_SERVICE_OFFER_GROUP_ID_UNIQUE` (`ACCOUNT_SUBSCRIPTION_SERVICE_OFFER_GROUP_ID` ASC),
                                                                     CONSTRAINT `fk_ACCOUNT_SUBSCRIPTION_CONTRACT_CONTRACT1`
                                                                         FOREIGN KEY (`CONTRACT_ID`)
                                                                             REFERENCES `c4e`.`CONTRACT` (`ID`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION,
                                                                     CONSTRAINT `fk_ACCOUNT_SUBSCRIPTION_CONTRACT_ACCOUNT_SUBSCRIPTION1`
                                                                         FOREIGN KEY (`ACCOUNT_SUBSCRIPTION_ACCOUNT_ID` , `ACCOUNT_SUBSCRIPTION_PROVIDER_ID` , `ACCOUNT_SUBSCRIPTION_SERVICE_OFFER_GROUP_ID`)
                                                                             REFERENCES `c4e`.`ACCOUNT_SUBSCRIPTION` (`ACCOUNT_ID` , `PROVIDER_ID` , `SERVICE_OFFER_GROUP_ID`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`INVOICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`INVOICE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`INVOICE` (
                                               `ID` BIGINT NOT NULL AUTO_INCREMENT,
                                               `INVOICE_NUMER` VARCHAR(55) NULL,
                                               `CONTRACT_ID` BIGINT NOT NULL,
                                               `STATUS` ENUM('ISSUED', 'PAID') NULL,
                                               PRIMARY KEY (`ID`),
                                               UNIQUE INDEX `INVOICE_NUMER_UNIQUE` (`INVOICE_NUMER` ASC),
                                               INDEX `fk_INVOICE_CONTRACT1_idx` (`CONTRACT_ID` ASC),
                                               CONSTRAINT `fk_INVOICE_CONTRACT1`
                                                   FOREIGN KEY (`CONTRACT_ID`)
                                                       REFERENCES `c4e`.`CONTRACT` (`ID`)
                                                       ON DELETE NO ACTION
                                                       ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`ROLE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`ROLE` (
                                            `ID` INT NOT NULL AUTO_INCREMENT,
                                            `NAME` ENUM('SUPER_ADMIN', 'ADMINISTRATOR_FULL', 'ADMINISTRATOR_BASIC', 'TRADER', 'SUPER_AGENT', 'AGENT', 'PROSUMER') NULL,
                                            PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`WORKER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`WORKER` ;

CREATE TABLE IF NOT EXISTS `c4e`.`WORKER` (
                                              `ID` INT NOT NULL AUTO_INCREMENT,
                                              `FIRST_NAME` VARCHAR(45) NULL,
                                              `LAST_NAME` VARCHAR(45) NULL,
                                              `EMAIL` VARCHAR(45) NOT NULL,
                                              `PHONE` VARCHAR(45) NULL,
                                              `WORK_START_DATE` DATETIME NULL,
                                              `WORK_END_DATE` DATETIME NULL,
                                              `STREET` VARCHAR(45) NULL,
                                              `CITY` VARCHAR(45) NULL,
                                              `POSTAL_CODE` VARCHAR(45) NULL,
                                              `PROVINCE` VARCHAR(45) NULL,
                                              `BUILDING_NUMBER` VARCHAR(45) NULL,
                                              `APARTMENT_NUMBER` VARCHAR(45) NULL,
                                              `COUNTRY` VARCHAR(45) NULL,
                                              `SUPERVISOR` INT NULL,
                                              `BLOCKCHAIN_ACC_ADDRESS` VARCHAR(75) NOT NULL,
                                              `PROVIDER_ID` INT NOT NULL,
                                              PRIMARY KEY (`ID`),
                                              UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
                                              UNIQUE INDEX `BLOCKCHAIN_ADDRESS_UNIQUE` (`BLOCKCHAIN_ACC_ADDRESS` ASC),
                                              INDEX `fk_WORKER_PROVIDER1_idx` (`PROVIDER_ID` ASC),
                                              INDEX `fk_WORKER_WORKER1_idx` (`SUPERVISOR` ASC),
                                              CONSTRAINT `fk_WORKER_PROVIDER1`
                                                  FOREIGN KEY (`PROVIDER_ID`)
                                                      REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION,
                                              CONSTRAINT `fk_WORKER_WORKER1`
                                                  FOREIGN KEY (`SUPERVISOR`)
                                                      REFERENCES `c4e`.`WORKER` (`ID`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`USER` ;

CREATE TABLE IF NOT EXISTS `c4e`.`USER` (
                                            `ID` INT NOT NULL AUTO_INCREMENT,
                                            `LOGIN` VARCHAR(45) NOT NULL,
                                            `PASSWORD` TEXT NOT NULL,
                                            `ACTIVE` TINYINT NULL DEFAULT 1,
                                            `MUST_CHANGE_PASSWORD` TINYINT NOT NULL DEFAULT 0,
                                            `ACTIVATION_CODE` VARCHAR(45) NULL,
                                            `PROVIDER_ID` INT NOT NULL,
                                            `WORKER_ID` INT NOT NULL,
                                            `CUSTOMER_ACCOUNT_ID` INT NOT NULL,
                                            `ROLE_ID` INT NOT NULL,
                                            PRIMARY KEY (`ID`),
                                            UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC),
                                            INDEX `fk_USER_PROVIDER1_idx` (`PROVIDER_ID` ASC),
                                            INDEX `fk_USER_WORKER1_idx` (`WORKER_ID` ASC),
                                            INDEX `fk_USER_CUSTOMER_ACCOUNT1_idx` (`CUSTOMER_ACCOUNT_ID` ASC),
                                            INDEX `fk_USER_ROLE1_idx` (`ROLE_ID` ASC),
                                            CONSTRAINT `fk_USER_PROVIDER1`
                                                FOREIGN KEY (`PROVIDER_ID`)
                                                    REFERENCES `c4e`.`PROVIDER` (`ID`)
                                                    ON DELETE NO ACTION
                                                    ON UPDATE NO ACTION,
                                            CONSTRAINT `fk_USER_WORKER1`
                                                FOREIGN KEY (`WORKER_ID`)
                                                    REFERENCES `c4e`.`WORKER` (`ID`)
                                                    ON DELETE NO ACTION
                                                    ON UPDATE NO ACTION,
                                            CONSTRAINT `fk_USER_CUSTOMER_ACCOUNT1`
                                                FOREIGN KEY (`CUSTOMER_ACCOUNT_ID`)
                                                    REFERENCES `c4e`.`CUSTOMER_ACCOUNT` (`ID`)
                                                    ON DELETE NO ACTION
                                                    ON UPDATE NO ACTION,
                                            CONSTRAINT `fk_USER_ROLE1`
                                                FOREIGN KEY (`ROLE_ID`)
                                                    REFERENCES `c4e`.`ROLE` (`ID`)
                                                    ON DELETE NO ACTION
                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`PARAMETER_NAME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`PARAMETER_NAME` ;

CREATE TABLE IF NOT EXISTS `c4e`.`PARAMETER_NAME` (
                                                      `ID` INT NOT NULL AUTO_INCREMENT,
                                                      `NAME` VARCHAR(45) NOT NULL,
                                                      PRIMARY KEY (`ID`),
                                                      UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`TARIFF_GROUP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`TARIFF_GROUP` ;

CREATE TABLE IF NOT EXISTS `c4e`.`TARIFF_GROUP` (
                                                    `ID` INT NOT NULL AUTO_INCREMENT,
                                                    `NAME` VARCHAR(45) NOT NULL,
                                                    `START_DATE` DATETIME NOT NULL,
                                                    `END_DATE` DATETIME NOT NULL,
                                                    `DISTRIBUTION_NETWORK_OPERATOR_ID` INT NOT NULL,
                                                    `TARIFF_GROUP_LABEL_NAME` VARCHAR(45) NOT NULL,
                                                    PRIMARY KEY (`ID`),
                                                    INDEX `fk_TARIFF_GROUP_DISTRIBUTION_NETWORK_OPERATOR1_idx` (`DISTRIBUTION_NETWORK_OPERATOR_ID` ASC),
                                                    INDEX `fk_TARIFF_GROUP_TARIFF_GROUP_LABEL1_idx` (`TARIFF_GROUP_LABEL_NAME` ASC),
                                                    CONSTRAINT `fk_TARIFF_GROUP_DISTRIBUTION_NETWORK_OPERATOR1`
                                                        FOREIGN KEY (`DISTRIBUTION_NETWORK_OPERATOR_ID`)
                                                            REFERENCES `c4e`.`DISTRIBUTION_NETWORK_OPERATOR` (`ID`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION,
                                                    CONSTRAINT `fk_TARIFF_GROUP_TARIFF_GROUP_LABEL1`
                                                        FOREIGN KEY (`TARIFF_GROUP_LABEL_NAME`)
                                                            REFERENCES `c4e`.`TARIFF_GROUP_LABEL` (`NAME`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`TARIFF_GROUP_PARAMETER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`TARIFF_GROUP_PARAMETER` ;

CREATE TABLE IF NOT EXISTS `c4e`.`TARIFF_GROUP_PARAMETER` (
                                                              `ID` INT NOT NULL AUTO_INCREMENT,
                                                              `PRICE` FLOAT NOT NULL,
                                                              `PARAMETER_NAME_ID` INT NOT NULL,
                                                              `TARIFF_GROUP_ID` INT NOT NULL,
                                                              PRIMARY KEY (`ID`),
                                                              INDEX `fk_TARIFF_GROUP_PARAMETER_PARAMETER_NAME1_idx` (`PARAMETER_NAME_ID` ASC),
                                                              INDEX `fk_TARIFF_GROUP_PARAMETER_TARIFF_GROUP1_idx` (`TARIFF_GROUP_ID` ASC),
                                                              CONSTRAINT `fk_TARIFF_GROUP_PARAMETER_PARAMETER_NAME1`
                                                                  FOREIGN KEY (`PARAMETER_NAME_ID`)
                                                                      REFERENCES `c4e`.`PARAMETER_NAME` (`ID`)
                                                                      ON DELETE NO ACTION
                                                                      ON UPDATE NO ACTION,
                                                              CONSTRAINT `fk_TARIFF_GROUP_PARAMETER_TARIFF_GROUP1`
                                                                  FOREIGN KEY (`TARIFF_GROUP_ID`)
                                                                      REFERENCES `c4e`.`TARIFF_GROUP` (`ID`)
                                                                      ON DELETE NO ACTION
                                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`SETTINGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`SETTINGS` ;

CREATE TABLE IF NOT EXISTS `c4e`.`SETTINGS` (
                                                `ID` INT NOT NULL AUTO_INCREMENT,
                                                `NAME` VARCHAR(45) NULL,
                                                `VALUE` VARCHAR(45) NULL,
                                                `TYPE` ENUM('INTEGER', 'BOOLEAN', 'FLOAT') NULL,
                                                PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`VAT_RATES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`VAT_RATES` ;

CREATE TABLE IF NOT EXISTS `c4e`.`VAT_RATES` (
                                                 `ID` INT NOT NULL AUTO_INCREMENT,
                                                 `DESCRIPTION` VARCHAR(45) NULL,
                                                 `GROUP` ENUM('Gxx', 'OWN_USAGE', 'RESALE') NULL,
                                                 `VALUE` SMALLINT NULL,
                                                 `START_DATE` DATE NULL,
                                                 `END_DATE` DATE NULL,
                                                 PRIMARY KEY (`ID`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`ENERGY_PRODUCTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`ENERGY_PRODUCTION` ;

CREATE TABLE IF NOT EXISTS `c4e`.`ENERGY_PRODUCTION` (
                                                         `ID` INT NOT NULL AUTO_INCREMENT,
                                                         `START_DATE` DATE NULL,
                                                         `END_DATE` DATE NULL,
                                                         `ENERGY_AMOUNT` INT NULL,
                                                         `ENERGY_AMOUNT_UNITS` ENUM('kWh', 'MWh') NULL,
                                                         `NET_PRICE` FLOAT NULL,
                                                         `NET_VALUE` FLOAT NULL,
                                                         `CONTRACT_ID` BIGINT NOT NULL,
                                                         `SERVICE_ACCESS_POINT_ID` INT NOT NULL,
                                                         PRIMARY KEY (`ID`),
                                                         INDEX `fk_ENERGY_PRODUCTION_CONTRACT1_idx` (`CONTRACT_ID` ASC),
                                                         INDEX `fk_ENERGY_PRODUCTION_SERVICE_ACCESS_POINT1_idx` (`SERVICE_ACCESS_POINT_ID` ASC),
                                                         CONSTRAINT `fk_ENERGY_PRODUCTION_CONTRACT1`
                                                             FOREIGN KEY (`CONTRACT_ID`)
                                                                 REFERENCES `c4e`.`CONTRACT` (`ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION,
                                                         CONSTRAINT `fk_ENERGY_PRODUCTION_SERVICE_ACCESS_POINT1`
                                                             FOREIGN KEY (`SERVICE_ACCESS_POINT_ID`)
                                                                 REFERENCES `c4e`.`SERVICE_ACCESS_POINT` (`ID`)
                                                                 ON DELETE NO ACTION
                                                                 ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`ENERGY_EXCESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`ENERGY_EXCESS` ;

CREATE TABLE IF NOT EXISTS `c4e`.`ENERGY_EXCESS` (
                                                     `ID` INT NOT NULL AUTO_INCREMENT,
                                                     `PERIOD` SMALLINT NOT NULL,
                                                     `CURRENT_ENERGY_CONSUMPTION` INT NULL,
                                                     `CURRENT_ENERGY_EXCESS` INT NULL,
                                                     `PREVIOUS_ENERGY_EXCESS` INT NULL,
                                                     `ENERGY_EXCESS_USAGE` INT NULL,
                                                     `ENERGY_EXCESS_TRANSFER` INT NULL,
                                                     `SERVICE_ACCESS_POINT_ID` INT NOT NULL,
                                                     PRIMARY KEY (`ID`),
                                                     INDEX `fk_ENERGY_EXCESS_SERVICE_ACCESS_POINT1_idx` (`SERVICE_ACCESS_POINT_ID` ASC),
                                                     CONSTRAINT `fk_ENERGY_EXCESS_SERVICE_ACCESS_POINT1`
                                                         FOREIGN KEY (`SERVICE_ACCESS_POINT_ID`)
                                                             REFERENCES `c4e`.`SERVICE_ACCESS_POINT` (`ID`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`OFFER_STATUSES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`OFFER_STATUSES` ;

CREATE TABLE IF NOT EXISTS `c4e`.`OFFER_STATUSES` (
                                                      `NAME` VARCHAR(10) NOT NULL,
                                                      PRIMARY KEY (`NAME`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`CONTRACT_STATUSES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`CONTRACT_STATUSES` ;

CREATE TABLE IF NOT EXISTS `c4e`.`CONTRACT_STATUSES` (
                                                         `NAME` VARCHAR(10) NOT NULL,
                                                         PRIMARY KEY (`NAME`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`REGION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`REGION` ;

CREATE TABLE IF NOT EXISTS `c4e`.`REGION` (
                                              `ID` INT NOT NULL,
                                              `NAME` VARCHAR(45) NULL,
                                              `DISTRIBUTION_NETWORK_OPERATOR_ID` INT NOT NULL,
                                              PRIMARY KEY (`ID`),
                                              INDEX `fk_REGION_DISTRIBUTION_NETWORK_OPERATOR1_idx` (`DISTRIBUTION_NETWORK_OPERATOR_ID` ASC),
                                              CONSTRAINT `fk_REGION_DISTRIBUTION_NETWORK_OPERATOR1`
                                                  FOREIGN KEY (`DISTRIBUTION_NETWORK_OPERATOR_ID`)
                                                      REFERENCES `c4e`.`DISTRIBUTION_NETWORK_OPERATOR` (`ID`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c4e`.`ZONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `c4e`.`ZONE` ;

CREATE TABLE IF NOT EXISTS `c4e`.`ZONE` (
                                            `ID` INT NOT NULL AUTO_INCREMENT,
                                            `DESCRIPTION` VARCHAR(100) NULL,
                                            `HOURS` VARCHAR(45) NULL,
                                            `NET_PRICE` FLOAT NOT NULL,
                                            `UNITS` ENUM('kWh', 'MWh') NOT NULL,
                                            `RATING_PLAN_ID` BIGINT NOT NULL,
                                            PRIMARY KEY (`ID`),
                                            INDEX `fk_ZONE_RATING_PLAN1_idx` (`RATING_PLAN_ID` ASC),
                                            CONSTRAINT `fk_ZONE_RATING_PLAN1`
                                                FOREIGN KEY (`RATING_PLAN_ID`)
                                                    REFERENCES `c4e`.`RATING_PLAN` (`ID`)
                                                    ON DELETE NO ACTION
                                                    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;